export interface Guitar {
  id: number;
  title: string;
  vendorCode: string;
  reviews: string;
  rating: number;
  article: string;
  type: string;
  strings: number;
  description: string;
  price: number;
  stocked: boolean;
  image: string;
  quantity?: number; // Optional property for quantity in the cart
}

const Guitars: Guitar[] = [
  {
    id: 1,
    title: "СURT Z30 Plus Acoustics",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4,
    article: "SO754565",
    type: "Электрогитара",
    strings: 7,
    description: "Электрогитара с 7 струнами, идеальная для",
    price: 12000,
    stocked: true,
    image: "/image/ElectroAcoustic.png",
  },
  {
    id: 2,
    title: "СURT Z30 Plus",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754566",
    type: "Электрогитара",
    strings: 6,
    description: "Электрогитара с 6 струнами, идеальная для",
    price: 9700,
    stocked: true,
    image: "/image/Electro.png",
  },
  {
    id: 3,
    title: "Честер Bass",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754567",
    type: "Акустическая",
    strings: 7,
    description: "Акустическая гитара с 7 струнами, идеальная для",
    price: 15000,
    stocked: true,
    image: "/image/ElectroBass.png",
  },
  {
    id: 4,
    title: "Укулеле",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754568",
    type: "Укулеле",
    strings: 4,
    description: "Укулеле с 4 струнами, идеальная для",
    price: 4780,
    stocked: false,
    image: "/image/Ukulele.png",
  },
  {
    id: 5,
    title: "Укулеле1",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754568",
    type: "Укулеле",
    strings: 5,
    description: "Укулеле с 4 струнами, идеальная для",
    price: 6789,
    stocked: false,
    image: "/image/Ukulele.png",
  },
  {
    id: 6,
    title: "СURT Z30 Plus Acoustics1",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4,
    article: "SO754565",
    type: "Электрогитара",
    strings: 4,
    description: "Электрогитара с 7 струнами, идеальная для",
    price: 12000,
    stocked: true,
    image: "/image/ElectroAcoustic.png",
  },
  {
    id: 7,
    title: "СURT Z30 Plus1",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754566",
    type: "Электрогитара",
    strings: 6,
    description: "Электрогитара с 6 струнами, идеальная для",
    price: 9700,
    stocked: true,
    image: "/image/Electro.png",
  },
  {
    id: 8,
    title: "Честер Bass1",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754567",
    type: "Акустическая",
    strings: 6,
    description: "Акустическая гитара с 7 струнами, идеальная для",
    price: 15000,
    stocked: true,
    image: "/image/ElectroBass.png",
  },
  {
    id: 9,
    title: "Укулеле2",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754568",
    type: "Укулеле",
    strings: 4,
    description: "Укулеле с 4 струнами, идеальная для",
    price: 4780,
    stocked: false,
    image: "/image/Ukulele.png",
  },
  {
    id: 10,
    title: "Укулеле3",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754568",
    type: "Укулеле",
    strings: 5,
    description: "Укулеле с 4 струнами, идеальная для",
    price: 6789,
    stocked: false,
    image: "/image/Ukulele.png",
  },
  {
    id: 11,
    title: "СURT Z30 Plus Acoustics2",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4,
    article: "SO754565",
    type: "Электрогитара",
    strings: 7,
    description: "Электрогитара с 7 струнами, идеальная для",
    price: 12000,
    stocked: true,
    image: "/image/ElectroAcoustic.png",
  },
  {
    id: 12,
    title: "СURT Z30 Plus2",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754566",
    type: "Электрогитара",
    strings: 4,
    description: "Электрогитара с 6 струнами, идеальная для",
    price: 9700,
    stocked: true,
    image: "/image/Electro.png",
  },
  {
    id: 13,
    title: "Честер Bass2",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754567",
    type: "Акустическая",
    strings: 12,
    description: "Акустическая гитара с 7 струнами, идеальная для",
    price: 15000,
    stocked: true,
    image: "/image/ElectroBass.png",
  },
  {
    id: 14,
    title: "Укулеле4",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754568",
    type: "Укулеле",
    strings: 4,
    description: "Укулеле с 4 струнами, идеальная для",
    price: 4780,
    stocked: false,
    image: "/image/Ukulele.png",
  },
  {
    id: 15,
    title: "Укулеле5",
    vendorCode: "SO757575",
    reviews: "",
    rating: 4.5,
    article: "SO754568",
    type: "Укулеле",
    strings: 5,
    description: "Укулеле с 4 струнами, идеальная для",
    price: 6789,
    stocked: false,
    image: "/image/Ukulele.png",
  },
];

export default Guitars;
